### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by ByeonYeongsin** [kaist-dmlab/MG-TAR#11]
Can you provide the version of other library with scikit-learn==1.1.0?

**Comment by itouchz** [comment]
Since we do not know about the dependencies of the scikit-learn 1.10, you can install scikit-learn 1.1 first and examine any conflicts via `pip check` whether which version of the rerequied packages/libraries conflict with the scikit-learn. Then, you can install them accordingly. Thank you!
