### ISSUE TITLE
Performance with respect to prediction time length

### ISSUE THREAD

**Issue by bamiikim** [kaist-dmlab/MG-TAR#12]
Thank you for sharing your excellent work!

I have one question: I'm curious if the performance of the predictive model varies as the prediction time horizon extends. The reported training data length is 6 days, but can it be used for problems that involve predicting one month or several months into the future?

I appreciate your response in advance.

**Comment by itouchz** [comment]
Yes, we can use it to predict longer period, but it may require more traning samples. We also discuss the relevant problem in the Limitations section.
